
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:13 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      msbuild 버전 17.9.8+b34f75857(.NET Framework용)
      빌드 시작: 2025-06-14 오후 1:02:47
      
      1 노드의 "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdC.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"에 연결(touching)하고 있습니다.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate"에 연결(touching)하고 있습니다.
      "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:00.92
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/4.0.2/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      msbuild 버전 17.9.8+b34f75857(.NET Framework용)
      빌드 시작: 2025-06-14 오후 1:02:48
      
      1 노드의 "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"에 연결(touching)하고 있습니다.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate"에 연결(touching)하고 있습니다.
      "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\4.0.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:00.66
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/4.0.2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-f1psyw"
      binary: "C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-f1psyw"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-f1psyw'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_81a18.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        msbuild 버전 17.9.8+b34f75857(.NET Framework용)
        빌드 시작: 2025-06-14 오후 1:02:49
        
        1 노드의 "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-f1psyw\\cmTC_81a18.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_81a18.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-f1psyw\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_81a18.dir\\Debug\\cmTC_81a18.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_81a18.dir\\Debug\\cmTC_81a18.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
          "cmTC_81a18.dir\\Debug\\cmTC_81a18.tlog\\unsuccessfulbuild"에 연결(touching)하고 있습니다.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_81a18.dir\\Debug\\\\" /Fd"cmTC_81a18.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.36.32545(x64)
          CMakeCCompilerABI.c
          Copyright (c) Microsoft Corporation. All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_81a18.dir\\Debug\\\\" /Fd"cmTC_81a18.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-f1psyw\\Debug\\cmTC_81a18.exe" /INCREMENTAL /ILK:"cmTC_81a18.dir\\Debug\\cmTC_81a18.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-f1psyw/Debug/cmTC_81a18.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-f1psyw/Debug/cmTC_81a18.lib" /MACHINE:X64  /machine:x64 cmTC_81a18.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_81a18.vcxproj -> C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-f1psyw\\Debug\\cmTC_81a18.exe
        FinalizeBuildStatus:
          "cmTC_81a18.dir\\Debug\\cmTC_81a18.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_81a18.dir\\Debug\\cmTC_81a18.tlog\\cmTC_81a18.lastbuildstate"에 연결(touching)하고 있습니다.
        "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-f1psyw\\cmTC_81a18.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.71
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.36.32545.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-how01u"
      binary: "C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-how01u"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-how01u'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_4738a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        msbuild 버전 17.9.8+b34f75857(.NET Framework용)
        빌드 시작: 2025-06-14 오후 1:02:50
        
        1 노드의 "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-how01u\\cmTC_4738a.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_4738a.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-how01u\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_4738a.dir\\Debug\\cmTC_4738a.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_4738a.dir\\Debug\\cmTC_4738a.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
          "cmTC_4738a.dir\\Debug\\cmTC_4738a.tlog\\unsuccessfulbuild"에 연결(touching)하고 있습니다.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_4738a.dir\\Debug\\\\" /Fd"cmTC_4738a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.36.32545(x64)
          CMakeCXXCompilerABI.cpp
          Copyright (c) Microsoft Corporation. All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_4738a.dir\\Debug\\\\" /Fd"cmTC_4738a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-4.0\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-how01u\\Debug\\cmTC_4738a.exe" /INCREMENTAL /ILK:"cmTC_4738a.dir\\Debug\\cmTC_4738a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-how01u/Debug/cmTC_4738a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/GameMathSource/gamemath-4-1/gamemath-4-1/Project/CMakeFiles/CMakeScratch/TryCompile-how01u/Debug/cmTC_4738a.lib" /MACHINE:X64  /machine:x64 cmTC_4738a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_4738a.vcxproj -> C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-how01u\\Debug\\cmTC_4738a.exe
        FinalizeBuildStatus:
          "cmTC_4738a.dir\\Debug\\cmTC_4738a.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_4738a.dir\\Debug\\cmTC_4738a.tlog\\cmTC_4738a.lastbuildstate"에 연결(touching)하고 있습니다.
        "C:\\GameMathSource\\gamemath-4-1\\gamemath-4-1\\Project\\CMakeFiles\\CMakeScratch\\TryCompile-how01u\\cmTC_4738a.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.71
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:227 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(|\\.[a-rt-z][a-z]*|\\.s[a-np-z][a-z]*|\\.so[a-z]+)|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CMakeDetermineLinkerId.cmake:36 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:270 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.36.32545.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
